name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ubuntu@51.20.135.184
        
        username: ubuntu
        key: ${{ secrets.PRIVATE_SSH_KEY}}
        port: 22
        script: 
            cd 100devs-ci-cd
            git pull
            npm install
            npm run build
            npm run start
